class Foo {
    function toss(this) throws {
        throw Error::from_errno(0)
    }
}

function main() {
    try {
        let foo = Foo()
        foo.toss()
    } catch err {
        println("PASS")
    }
}